name: Full Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-feature-engineering:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Feature Engineering Workflow
        uses: actions/github-script@v6
        with:
          script: |
            const { data: run } = await github.actions.createWorkflowDispatch({
              owner: 'mahi-DR',
              repo: 'citibike_pred',
              workflow_id: 'feature-engineering.yml',  # This should match the name of your workflow file
              ref: 'main'  # The branch to trigger the workflow
            })

  trigger-inference:
    needs: trigger-feature-engineering  # Ensure this runs after the feature-engineering job
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Inference Workflow
        uses: actions/github-script@v6
        with:
          script: |
            const { data: run } = await github.actions.createWorkflowDispatch({
              owner: 'mahi-DR',
              repo: 'citibike_pred',
              workflow_id: 'inference.yml',  # This should match the name of your workflow file
              ref: 'main'  # The branch to trigger the workflow
            })

  trigger-model-training:
    needs: trigger-inference  # Ensure this runs after the inference job
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Model Training Workflow
        uses: actions/github-script@v6
        with:
          script: |
            const { data: run } = await github.actions.createWorkflowDispatch({
              owner: 'mahi-DR',
              repo: 'citibike_pred',
              workflow_id: 'model-training.yml',  # This should match the name of your workflow file
              ref: 'main'  # The branch to trigger the workflow
            })
