name: Full Pipeline

on:
  workflow_run:
    workflows: ["Feature Engineering", "Inference", "Model Training"]  # List the workflows you want to trigger based on success
    types:
      - completed

jobs:
  feature-engineering:
    runs-on: ubuntu-latest
    steps:
      - name: Run Feature Engineering
        uses: actions/checkout@v2
        run: |
          echo "Running feature engineering step..."

  inference:
    needs: feature-engineering
    runs-on: ubuntu-latest
    steps:
      - name: Run Inference
        uses: actions/checkout@v2
        run: |
          echo "Running inference step..."

  model-training:
    needs: inference
    runs-on: ubuntu-latest
    steps:
      - name: Run Model Training
        uses: actions/checkout@v2
        run: |
          echo "Running model training step..."
